spring.application.name=fitness-monolith

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.json_format_mapper=jackson


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
logging.level.org.hibernate.SQL=DEBUG